### Get schools

GET http://127.0.0.1:8080/api/v1/schools?offset=1&limit=10&school=uvic
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
###
GET http://127.0.0.1:8080/api/v1/schools?offset=1&limit=10&lat=40.799391&lon=-77.860863&radius=1000
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
###
GET http://127.0.0.1:8080/api/v1/schools?offset=1&limit=10
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H

### Watch a school

POST http://127.0.0.1:8080/api/v1/schools/watch
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3YmFiYWFiYTEwNWFkZDZiM2ZiYjlmZjNmZjVmZTNkY2E0Y2VkYTEiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODY5MTA3MTQsInVzZXJfaWQiOiJIOU11OG9hOHI1WmpaREh5OXdXNkF4SElvaksyIiwic3ViIjoiSDlNdThvYThyNVpqWkRIeTl3VzZBeEhJb2pLMiIsImlhdCI6MTY4NjkxMDcxNCwiZXhwIjoxNjg2OTE0MzE0LCJlbWFpbCI6InVzZXI3QHV2aWMuY2EiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjdAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Fz12669YpWc2GMWvkC1axQ2fOWVfHIx7QT1kiwow5zYKD3t5J0dUpvB9SK7KPJkigwzvWA7F1grKR9PnQRclGwE73-oZxBC3wfFKV-z0nfAZk26ApWWCDdZ_OPLETAzwk7SkrRkOPbpUD1Pvq7vOdBfskfUY1FFPWBRIg4Wwzc6Bdlkh6K2KWB0VBfJtRBGbdNVPiNZy-HTf6LJkMKOFksUMkMicr7BX7dmOnO729v4bYCRC0yX0U9MM9aFTfP6shq-ldYs6z3Lr8Eg4VXqFMIaVKpPw_1bD6X6G-PG1mVmMsTRhr8D5HZI7rBK57CW353YVGsmq_TMWfHMWIa8zPw

{
    "school_id": 1
}