### Create report

POST http://127.0.0.1:8080/api/v1/reports/report
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6WyJhZG1pbiJdLCJzeW5jIjp0cnVlLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXVkIjoiY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXV0aF90aW1lIjoxNjg5OTMyNzc1LCJ1c2VyX2lkIjoiZU5MVXZXZ3hJZ1o3OXQycFptTTE1RHhYTTZ1MiIsInN1YiI6ImVOTFV2V2d4SWdaNzl0MnBabU0xNUR4WE02dTIiLCJpYXQiOjE2ODk5MzI3NzUsImV4cCI6MTY4OTkzNjM3NSwiZW1haWwiOiJvb2JlckB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm9vYmVyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.gT6UAHqDCpA0zgTr08XidAurCyvIszEZvHMO1qHde1R5YQLVquv-FXcw3kf_W9fO3V9t73k-nXG8s1-Y4RlbhKnYhCVhLAd-lQPlGNRpyFky-gPu7Gevd6GHV4z6-dgkMkmur613HpXHEjumbOfybjLo14EvSzQeIgZTjddzGt5JkguEUChMWbSDrad4I2RpwZUfzVxpxBzTdmHhTN4bKWnS2bDKpiDCjg6FrrAx65r5JXMITaV7Mjr1RcdK3zuJD2ZTTWrbCGFPOQpD_HVj7gPn8RksQuOGELnBEWmRyJaSqBBYxLcIPBfWBoW1vQt-Jfw34BxIi960OEmH7sV8VQ

{
    "content_id": 1,
    "content_type": "post",
    "type": "nsfw",
    "description": "This is an nsfw post"
}

### Fetch your reports

GET http://127.0.0.1:8080/api/v1/reports/reports
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6WyJhZG1pbiJdLCJzeW5jIjp0cnVlLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXVkIjoiY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXV0aF90aW1lIjoxNjg5OTMyNzc1LCJ1c2VyX2lkIjoiZU5MVXZXZ3hJZ1o3OXQycFptTTE1RHhYTTZ1MiIsInN1YiI6ImVOTFV2V2d4SWdaNzl0MnBabU0xNUR4WE02dTIiLCJpYXQiOjE2ODk5MzI3NzUsImV4cCI6MTY4OTkzNjM3NSwiZW1haWwiOiJvb2JlckB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm9vYmVyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.gT6UAHqDCpA0zgTr08XidAurCyvIszEZvHMO1qHde1R5YQLVquv-FXcw3kf_W9fO3V9t73k-nXG8s1-Y4RlbhKnYhCVhLAd-lQPlGNRpyFky-gPu7Gevd6GHV4z6-dgkMkmur613HpXHEjumbOfybjLo14EvSzQeIgZTjddzGt5JkguEUChMWbSDrad4I2RpwZUfzVxpxBzTdmHhTN4bKWnS2bDKpiDCjg6FrrAx65r5JXMITaV7Mjr1RcdK3zuJD2ZTTWrbCGFPOQpD_HVj7gPn8RksQuOGELnBEWmRyJaSqBBYxLcIPBfWBoW1vQt-Jfw34BxIi960OEmH7sV8VQ

{
    "next": null
}

### get report by id

GET http://127.0.0.1:8080/api/v1/reports/report?id=1
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6WyJhZG1pbiJdLCJzeW5jIjp0cnVlLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXVkIjoiY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXV0aF90aW1lIjoxNjg5OTMyNzc1LCJ1c2VyX2lkIjoiZU5MVXZXZ3hJZ1o3OXQycFptTTE1RHhYTTZ1MiIsInN1YiI6ImVOTFV2V2d4SWdaNzl0MnBabU0xNUR4WE02dTIiLCJpYXQiOjE2ODk5MzI3NzUsImV4cCI6MTY4OTkzNjM3NSwiZW1haWwiOiJvb2JlckB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm9vYmVyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.gT6UAHqDCpA0zgTr08XidAurCyvIszEZvHMO1qHde1R5YQLVquv-FXcw3kf_W9fO3V9t73k-nXG8s1-Y4RlbhKnYhCVhLAd-lQPlGNRpyFky-gPu7Gevd6GHV4z6-dgkMkmur613HpXHEjumbOfybjLo14EvSzQeIgZTjddzGt5JkguEUChMWbSDrad4I2RpwZUfzVxpxBzTdmHhTN4bKWnS2bDKpiDCjg6FrrAx65r5JXMITaV7Mjr1RcdK3zuJD2ZTTWrbCGFPOQpD_HVj7gPn8RksQuOGELnBEWmRyJaSqBBYxLcIPBfWBoW1vQt-Jfw34BxIi960OEmH7sV8VQ


