### Create post

POST http://127.0.0.1:8080/api/v1/posts/create
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJkM2E0YTllYjY0OTk0YzUxM2YyYzhlMGMwMTY1MzEzN2U5NTg3Y2EiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODU4ODI1NDQsInVzZXJfaWQiOiJ5MHF3dE5teHNFZFE2bVlYQkduN1BJMEFxTFEyIiwic3ViIjoieTBxd3RObXhzRWRRNm1ZWEJHbjdQSTBBcUxRMiIsImlhdCI6MTY4NTg4MjU0NCwiZXhwIjoxNjg1ODg2MTQ0LCJlbWFpbCI6InVzZXIzQGV4YW1wbGUuZWR1IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXIzQGV4YW1wbGUuZWR1Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.B4_g8H2o5X71_HM6oFtSFEcLohZv_chj9CzaNrsY7WeN-rAWzTpNjg2nTb_8IwhlyUq8pxvVyle4_0NO7IegVwP4LO_zXyQ8xflmqO2LR1Jj-feYYzukFVjONyh6XPLJba9D64yU6iYnh4s0hJV-RmdnNJ7-neH3qfBg7C6LYfMlpOTpxIcEwyLYOB40BFPb4fdC3MFQiKC2y0Mn64zVFuzuaB9G7c-nNgh8sGCPiFRz2tdRczF5F4zkiReI7l26PywTFpB1KgUI8JcPnEaA1KBMcdExW0u0cClT9RWokAaUBigVXkURSHDS47DYGlKYewd_hMPBUBOx49PafpQX5w

{
    "title": "   test value, oh, yes, cool title   ",
    "body": null
}