### Create post

POST http://127.0.0.1:8080/api/v1/posts/create
Content-Type: application/json
X-AppCheck-Token: owzN/GzTL4oXRCkRfFkCxrJR1-5ltFXl7gSdBuDa1UfFyKlLho?IBAK3jJFfy7Ll0cQhrm8sDfz4qwgU?ZegJqcEhcM?QnO8C/mvSOhPfFrErRtaX-!FxH9jZRzF5TpKy/G?4Gl8Q9N9vGsFPxSKSTWNtabRdFyDiyUZyix9o0vjwDdYkNESe97h4--OOCzRh//?VPVPUEVcHIwqJz/Q2qJ=fc-phSlS5QWd4Zqoa0r9r3EINgPjGAoexuSjkbx6
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJkM2E0YTllYjY0OTk0YzUxM2YyYzhlMGMwMTY1MzEzN2U5NTg3Y2EiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODU4NDUyMTMsInVzZXJfaWQiOiJ5MHF3dE5teHNFZFE2bVlYQkduN1BJMEFxTFEyIiwic3ViIjoieTBxd3RObXhzRWRRNm1ZWEJHbjdQSTBBcUxRMiIsImlhdCI6MTY4NTg0NTIxMywiZXhwIjoxNjg1ODQ4ODEzLCJlbWFpbCI6InVzZXIzQGV4YW1wbGUuZWR1IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXIzQGV4YW1wbGUuZWR1Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.lT7oPUZXporMEdqQsG0D3fM-szG06POoOmyLB5Vs6JJjGzJPHRh4IAtmliDWiXplQ6Yg68FpJ0nfuM-To2LMsKU3ajssZggz1Ubj5UcITJsVp1cMtAqJm7Z3Ny54gq9Rl1j2v5uszVpbt6XQCy3aP1CzIJa7rpQsERGoA9xLHCXfwXp8Yn1E8ommQdScjiWOEo_vP3ihdYsZVs7XA9_WumISELpw6Hqv4RdnY-4-oHlwiR2fMxkZBj4W2zaAAsW7Nr2pd8z90N_EqNTGjTGcHWTNVEjIDPSqVo4G9DrEdoVJ9-m86Y86JD2ES4hNM8b-EwR11qInTVBaInuFRqrv5A

{
    "title": null,
    "body": "999!"
}