### Create post

POST http://127.0.0.1:8080/api/v1/posts/create
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "title": "my post is cool",
    "body": "hey this is OP"
}

### Fetch hottest posts from a specific day

GET http://127.0.0.1:8080/api/v1/posts/hottest?day=2023-07-04
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

### Fetch a post by id

GET http://127.0.0.1:8080/api/v1/posts/post?id=1
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

### Fetch posts

GET http://127.0.0.1:8080/api/v1/posts/posts
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "sort": "new",
    "school": 1,
    "purge_cache": true,
    "session_key": "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
}

### Purge posts cache

DELETE http://127.0.0.1:8080/api/v1/posts/purge?session-key=6ba7b810-9dad-11d1-80b4-00c04fd430c8
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

### Sentiment anaylsis for posts by ID

GET http://127.0.0.1:8080/api/v1/posts/sentiment?id=1
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

### Fetch your posts

GET http://127.0.0.1:8080/api/v1/posts/your-posts
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "next": 1688460277629001
}

### Hide a post

PATCH  http://127.0.0.1:8080/api/v1/posts/hide
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "post_id": 2
}

### Edit your post

PATCH http://127.0.0.1:8080/api/v1/posts/edit
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "post_id": 1,
    "title": "title ah",
    "body": "body ah"
}