### Get User Stats

GET http://127.0.0.1:8080/api/v1/stats/user-stats
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXVkIjoiY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXV0aF90aW1lIjoxNjkwMDQ5MjAzLCJ1c2VyX2lkIjoibHhxbkNSYndIN2c1cXpyWDE4SDd1SXMyZ1VaMiIsInN1YiI6Imx4cW5DUmJ3SDdnNXF6clgxOEg3dUlzMmdVWjIiLCJpYXQiOjE2OTAwNDkyMDMsImV4cCI6MTY5MDA1MjgwMywiZW1haWwiOiJwbGVhc2VsZXRtZXNpZ25pbkB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInBsZWFzZWxldG1lc2lnbmluQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.BQWOeijidjAwj2wG4Iz0yF_j5WSM3pCrDkFE1pJQL8aS7og0X3h6fjP8fG4Rwwi3JkiqaYRX77s8YC_SLtYdMFbK9VbnsAGWlP54usO-AaoZnB-kio8Ul7ob8DmebNchIuqvtakLXQerMcbQLcVV4-cJxTO-qUfk-JvJ3ELKmIVuGwfwXZtpx5FD4R1CocO0z96HjcK7KKlZK6J73OFTY0L_AIOaFyTm_M4awzBZORXWnPIdeuSgHh3A-sLhoOXfcoUFBThcLt9d2aEHf8zXSsbJ7DZLUxTcVPyq1sx3mEz1Mes_W_iYpZcpw-gKtfooKnUxOnLT9EWt2CvjvbIZFA

