Enum "vote_score_value" {
	"1"
	"-1"
}

Table "comments" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"updated_on" timestamp   
 	"user_id" integer   
 	"post_id" integer   
 	"comment_id" integer   
 	"content" text   
 	"upvote" integer   
 	"downvote" integer   
 	"score" integer   
 	"hidden" boolean   
 } 
 
 Table "faculties" {
 	"id" integer  [primary key] 
 	"faculty" varchar(255)  
 } 
 
 Table "faculty" {
 	"id" integer  [primary key] 
 	"faculty" varchar(255)  
 } 
 
 Table "feedbacks" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"user_id" integer   
 	"content" text   
 } 
 
 Table "mod_levels" {
 	"id" integer  [primary key] 
 	"mod" varchar(20)  
 } 
 
 Table "posts" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"updated_on" timestamp   
 	"user_id" integer   
 	"school_id" integer   
 	"faculty_id" integer   
 	"title" varchar(255)  
 	"content" text   
 	"downvote" integer   
 	"upvote" integer   
 	"vote_score" integer   
 	"trending_score" real   
 	"hottest_on" date   
 	"hidden" boolean   
 } 
 
 Table "reports" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"reported_by" integer   
 	"user_id" integer   
 	"description" text   
 	"type" varchar(255)  
 	"result" text   
 	"user_alerted" boolean  [default: false] 
 } 
 
 Table "saved_comments" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"user_id" integer   
 	"comment_id" integer   
 } 
 
 Table "saved_posts" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"user_id" integer   
 	"post_id" integer   
 } 
 
 Table "schema_migrations" {
 	"version" bigint  [primary key] 
 	"dirty" boolean   
 } 
 
 Table "school_follows" {
 	"id" integer  [primary key] 
 	"user_id" integer   
 	"school_id" integer   
 } 
 
 Table "schools" {
 	"id" integer  [primary key] 
 	"name" varchar(255)  
 	"abbr" varchar(10)  
 	"lat" real   
 	"lon" real   
 	"domain" varchar(100)  
 } 
 
 Table "users" {
 	"id" integer  [primary key] 
 	"created_on" timestamp   
 	"email" varchar(100)  
 	"year_of_study" integer   
 	"faculty_id" integer   
 	"school_id" integer   
 	"mod_id" integer   
 } 
 
 Table "votes" {
 	"id" integer  [primary key] 
 	"vote" vote_score_value   
 	"user_id" integer   
 	"post_id" integer   
 	"comment_id" integer   
 } 
 
 
Ref: "comments".post_id > "posts".id
Ref: "comments".user_id > "users".id
Ref: "feedbacks".user_id > "users".id
Ref: "posts".faculty_id > "faculties".id
Ref: "posts".school_id > "schools".id
Ref: "posts".user_id > "users".id
Ref: "reports".reported_by > "users".id
Ref: "reports".user_id > "users".id
Ref: "saved_comments".comment_id > "comments".id
Ref: "saved_comments".user_id > "users".id
Ref: "saved_posts".post_id > "posts".id
Ref: "saved_posts".user_id > "users".id
Ref: "school_follows".school_id > "schools".id
Ref: "school_follows".user_id > "users".id
Ref: "users".school_id > "schools".id
Ref: "users".faculty_id > "faculty".id
Ref: "votes".comment_id > "comments".id
Ref: "votes".user_id > "users".id
Ref: "votes".post_id > "posts".id 
 
