version: "3.9"

services:
  db:
    container_name: confesi-db
    image: postgres:14.8-alpine
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confesi
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

  app:
    container_name: confesi-api
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 8080:8080
    links:
      - db
      - redis
    volumes:
      - .:/confesi
      - gohome:/go
    environment:
      PORT:
      POSTGRES_DSN:
      REDIS_CONN:
      PUBLIC_DOC_ACCESS:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      MASK_SECRET:
      GOCACHE: /go/cache

  redis:
      image: redis:alpine
      volumes:
        - redis-data:/data
      container_name: redis
      ports:
        - '6379:6379'

volumes:
  gohome:
  redis-data:
    driver: local