### Save content

POST http://127.0.0.1:8080/api/v1/saves/save
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3YmFiYWFiYTEwNWFkZDZiM2ZiYjlmZjNmZjVmZTNkY2E0Y2VkYTEiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODcwMDE5NzMsInVzZXJfaWQiOiI2ckZZaDBEeFlWVG90RU4zdXNXZFZmcENCM3MxIiwic3ViIjoiNnJGWWgwRHhZVlRvdEVOM3VzV2RWZnBDQjNzMSIsImlhdCI6MTY4NzAwMTk3NCwiZXhwIjoxNjg3MDA1NTc0LCJlbWFpbCI6InVzZXIxMDBAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ1c2VyMTAwQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.d5i1A9pg4xXRm5uIanJuH0sxDZm0-7XDc5s1u5Xcl3oaKcSoeV0oyLdN9H7NQ3Ccc-g556RLfYSw1Fh0x7mIUlfLVbK25gFB-Twl1_ILCq_CS1D46jrrcU5GqximfvbdmqY3XJdBGFY7-E7d8gMdQcRWL9e9n-4lXPMGXWe4jByNTDsSRgilVmwQvJDI3n1Ksasc3sWQmSkf1k6nfTt7S0uI4eVt6dMh1qv5CaJq-9IpSwCm9N9kBER38YltFZiVuFHfC70Q-HWtvNI-pdHGsAX7TEnkrR-VIrE7-QxeGOaafo92i_HvrKtXgMfP1rUH0Oa4VeZtvyXe3ebcQetb0Q

{
    "content_id": 3,
    "content_type": "post"
}

### Unsave content

DELETE http://127.0.0.1:8080/api/v1/saves/unsave
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3YmFiYWFiYTEwNWFkZDZiM2ZiYjlmZjNmZjVmZTNkY2E0Y2VkYTEiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODY3NDExODUsInVzZXJfaWQiOiJIOU11OG9hOHI1WmpaREh5OXdXNkF4SElvaksyIiwic3ViIjoiSDlNdThvYThyNVpqWkRIeTl3VzZBeEhJb2pLMiIsImlhdCI6MTY4Njc0MTE4NSwiZXhwIjoxNjg2NzQ0Nzg1LCJlbWFpbCI6InVzZXI3QHV2aWMuY2EiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjdAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Moj7mvaK3ii9d2Af4Jwnp-OG7ArlAvXecNmujlEcEv4birERKXQ_yYn7Dc9XJr8M2sTaJMOFfMjyb9GJx8GJNHcURDlnp0DHLRW-xN-_4t7yCs_WNGDvY-HyvF_LB-Yzkk-xw9uVvCAnH3qtPMH8iStVh1W32FuLZNtpxld6-0uSpkTPFRncPJxYsE4jQZFtx0ZGwpu-wcoK6dgHlnX9W82upnX6fCfIXo-YfgErPAYH-s5--3RvLVrUKVVcKX6DmHsxpdPerCVP_ZjFb9rFzrlKeSbNVE7tsQxMsSKjcZGOgJ7KvXyFaoWIpFPGrjfy3Zjc4S052gVKptfoLgpeog

{
    "content_id": 3,
    "content_type": "post"
}

### Fetch saved posts

GET http://127.0.0.1:8080/api/v1/saves/posts
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3YmFiYWFiYTEwNWFkZDZiM2ZiYjlmZjNmZjVmZTNkY2E0Y2VkYTEiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODcwMDE5NzMsInVzZXJfaWQiOiI2ckZZaDBEeFlWVG90RU4zdXNXZFZmcENCM3MxIiwic3ViIjoiNnJGWWgwRHhZVlRvdEVOM3VzV2RWZnBDQjNzMSIsImlhdCI6MTY4NzAwMTk3NCwiZXhwIjoxNjg3MDA1NTc0LCJlbWFpbCI6InVzZXIxMDBAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ1c2VyMTAwQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.d5i1A9pg4xXRm5uIanJuH0sxDZm0-7XDc5s1u5Xcl3oaKcSoeV0oyLdN9H7NQ3Ccc-g556RLfYSw1Fh0x7mIUlfLVbK25gFB-Twl1_ILCq_CS1D46jrrcU5GqximfvbdmqY3XJdBGFY7-E7d8gMdQcRWL9e9n-4lXPMGXWe4jByNTDsSRgilVmwQvJDI3n1Ksasc3sWQmSkf1k6nfTt7S0uI4eVt6dMh1qv5CaJq-9IpSwCm9N9kBER38YltFZiVuFHfC70Q-HWtvNI-pdHGsAX7TEnkrR-VIrE7-QxeGOaafo92i_HvrKtXgMfP1rUH0Oa4VeZtvyXe3ebcQetb0Q

{
    "next": 1687002016991
}

### Fetch saved comments

GET http://127.0.0.1:8080/api/v1/saves/comments
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3YmFiYWFiYTEwNWFkZDZiM2ZiYjlmZjNmZjVmZTNkY2E0Y2VkYTEiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODY4MjE0NjAsInVzZXJfaWQiOiJIOU11OG9hOHI1WmpaREh5OXdXNkF4SElvaksyIiwic3ViIjoiSDlNdThvYThyNVpqWkRIeTl3VzZBeEhJb2pLMiIsImlhdCI6MTY4NjgyMTQ2MSwiZXhwIjoxNjg2ODI1MDYxLCJlbWFpbCI6InVzZXI3QHV2aWMuY2EiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjdAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.JxyTJxKkaERphvkhgTTku392_ZxU3p48Tfa9BRR8nnrKaa_JiZjLkZZ8unKOcw0JERkTdlCt_EW4oOqE280U1PbxxA4QVDrizRFDkAu6Mh2GZw6P9hMcSp-AsopybKXaDcPhyerm4pngvkVEOCJhzMERwHwL9cAifN5B4myiC411-2TtrOtDaOS3ZzLxt6EkB6hajRH9tE1nsEkKwEY_387_moQ58iL6VONQTRNK-Qtg6lot7-zAcMrDSNzDKo82bgYoa6VYt7qOczgs953E1GNxSebMEgyi9FzyIpiF-yxo4UZQAlRVpqkmF92QZr6roM6tVj3ff6xHfnTtx1fAoA

{
    "next": 1686813826852
}