### remove FCM token

DELETE  http://127.0.0.1:8080/api/v1/notifications/token
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg

{
    "token": "eUMvIr2LwUunrtBhcWE0dQ:APA91bHA7wxFCx7xNNAJyR07XGw3cuzXcmU3MvjX4IC4-_KLLK0G5I8ZPXvR_i8lVk2h14REe8DzM7C64o-CSbBawLXTTjsdaJCL0NvuXTaJn95QZUujt7yuyhkGr5gashoV9DwiErLJ"
}

### add fcm token

POST  http://127.0.0.1:8080/api/v1/notifications/token
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg

{
    "token": "pd12dqUMvIr2LwUunrtBhcWE0dQ:APA91bHA7wxFCx7xNNAJyR07XGw3cuzXcmU3MvjX4IC4-_KLLK0G5I8ZPXvR_i8lVk2h14REe8DzM7C64o-CSbBawLXTTjsdaJCL0NvuXTaJn95QZUujt7yuyhkGr5gashoV9DwiErLJ"
}

### Get topic prefs

GET  http://127.0.0.1:8080/api/v1/notifications/topic-prefs
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg

### Set topic prefs

PUT  http://127.0.0.1:8080/api/v1/notifications/topic-prefs
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg

{
  "daily_hottest": true,
  "trending": false,
  "replies_to_your_comments": true,
  "comments_on_your_posts": true,
  "votes_on_your_comments": false,
  "votes_on_your_posts": false,
  "quotes_of_your_posts": false
}