### remove FCM token

DELETE  http://127.0.0.1:8080/api/v1/notifications/token
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "token": "eUMvIr2LwUunrtBhcWE0dQ:APA91bHA7wxFCx7xNNAJyR07XGw3cuzXcmU3MvjX4IC4-_KLLK0G5I8ZPXvR_i8lVk2h14REe8DzM7C64o-CSbBawLXTTjsdaJCL0NvuXTaJn95QZUujt7yuyhkGr5gashoV9DwiErLJ"
}

### add fcm token

POST  http://127.0.0.1:8080/api/v1/notifications/token
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
    "token": "pd12dqUMvIr2LwUunrtBhcWE0dQ:APA91bHA7wxFCx7xNNAJyR07XGw3cuzXcmU3MvjX4IC4-_KLLK0G5I8ZPXvR_i8lVk2h14REe8DzM7C64o-CSbBawLXTTjsdaJCL0NvuXTaJn95QZUujt7yuyhkGr5gashoV9DwiErLJ"
}

### Get topic prefs

GET  http://127.0.0.1:8080/api/v1/notifications/topic-prefs
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

### Set topic prefs

PUT  http://127.0.0.1:8080/api/v1/notifications/topic-prefs
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzgzODAsInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3ODM4MCwiZXhwIjoxNjg5NjgxOTgwLCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mF8wQr4MAnlOOM9yZU_IqGhYjyKLji2XrKA5ErqJs39syau45l20pcTjd87h93vFf77Qgi-F3owJoD3h58AqHso8in4MdPi2C5Xe17wHvR-rAJxvtxdFOEuwj-tYrhmLBpN4ucLx_xLTFcHpo4ndC7YePZQA5fcLWRrS43MD-tTByMPch1BVsO-tfQ9NJj2X-4oxQpY351ueZZeKyife60n6VQh2eO00TSIafWScPpbSj96j7cyifqVUWRPGOfw4VDkn80w5hWUuaFsxO_hiExKi7oR8xHpof8IijQ_BUf7quzoSSYq8sTKSPowclroHADkOf0_c0OEps9c1A27qFA

{
  "daily_hottest": true,
  "trending": false,
  "replies_to_your_comments": true,
  "comments_on_your_posts": true,
  "votes_on_your_comments": false,
  "votes_on_your_posts": false,
  "quotes_of_your_posts": false
}