### Vote

PUT http://127.0.0.1:8080/api/v1/votes/vote
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NzM5MjksInVzZXJfaWQiOiJSWXhlcDd6aEhmUHFxMHJvZFRwRHZ4SUFzczIyIiwic3ViIjoiUll4ZXA3emhIZlBxcTByb2RUcER2eElBc3MyMiIsImlhdCI6MTY4OTY3MzkyOSwiZXhwIjoxNjg5Njc3NTI5LCJlbWFpbCI6Im1vZDJAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtb2QyQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.OFAAexMT8i-SphQrHn94Ml-CRz-cFJb2mVCcCg2ypfQTI22zDKSeyKiOoR5_TdCRm1flY2IzLNxzHHV2ePk5zbHTN4srdDmPOVq7hgZYbuyxXeRmEvnLNNuFXvzHjAXe83PA8FBjgt2W5ya9hpum6Rv50FnS-5uxeDnneL3ytvRX5nj_W24Dfi_Z9xduhaxOa5vX9ez8FJ3ZoufylRTRBJGV_mVnGaYBFc_FMdXtLJXqoVbyWB6WxV4Et8Svci-2VsTVhITP5maUD14SxCGDWnVXo218UbdUXypAStDmcL1aiRo0SfrfJZM6ahSwswDsGLXHXYqYDgdiLWYuToh4KA

{
    "content_id": 120,
    "value": 1,
    "content_type": "comment"
}