### Create a comment 
### `parent_comment_id`: null | #

POST http://127.0.0.1:8080/api/v1/comments/create
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

{
    "post_id": 66,
    "parent_comment_id": 126,
    "content": "root-B-2"
}

### Hide a comment

PATCH  http://127.0.0.1:8080/api/v1/comments/hide
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

{
    "comment_id": 35
}

### Fetch root comments (optionally with some replies)
###
### IMPORTANT: sorting is offloaded to the client, comments returned in a jumbled order
### to reduce server load.

GET http://127.0.0.1:8080/api/v1/comments/roots
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

{
    "post_id": 66,
    "sort": "new",
    "purge_cache": true,
    "session_key": "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
}

### Fetch replies for a comment

GET http://127.0.0.1:8080/api/v1/comments/replies
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

{
    "parent_comment": 52,
    "next": 1688374719456041
}

### Purge comments cache

DELETE http://127.0.0.1:8080/api/v1/comments/purge?session-key=6ba7b810-9dad-11d1-80b4-00c04fd430c8
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

### Fetch a comment by id

GET http://127.0.0.1:8080/api/v1/comments/comment?id=109
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

### Fetch your comments

GET http://127.0.0.1:8080/api/v1/comments/your-comments
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWJiNGJkMWQwYzYxNDc2ZWIxYjcwYzNhNDdjMzE2ZDVmODkzMmIiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODcyMDA0OSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NzIwMDQ5LCJleHAiOjE2ODg3MjM2NDksImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YzRSWv868HkElliZjjpThEo5b3dc0gelDfJVvBE-XctEoWGxcZ6CZKgPYfFxIT0qbsBf7ldUrcQFnBOXHMEPNWsKNte4_tkqk1Ce5lZZsWcRFLReg6dGK__IHieL8vHbLp-DLYw-W2bu4TEjeYFdfhCbBsbFWzgFLQDuspHOsBqsz-xfUJ89OtZMQi60_CrlpE_BnxD99xks5urLV3dilqjS8-rFCO4fV-my40fGokt2CysamAPhxsMQqHazjr-kmgaCsMzXQtpGPeASZtZVrC3Sz4yMQcjj9xchsSnr6f4kzowl5sdKy42fXpPMXfIUazouP3TZq1cAUO6KDayQyQ

{
    "next": 1688642049100516
}