
### Get hidden log list

GET http://127.0.0.1:8080/api/v1/hide-log/your-hide-log
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg

{
    "next": 1689647419058834
}


### Get hidden content log by id

GET http://127.0.0.1:8080/api/v1/hide-log/hide-log?id=1
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbImFkbWluIl0sImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2ODk2NDk1ODksInVzZXJfaWQiOiJmNzZXdndxd08xZzI1c0luTVpQOENhRHFGcmIyIiwic3ViIjoiZjc2V3Z3cXdPMWcyNXNJbk1aUDhDYURxRnJiMiIsImlhdCI6MTY4OTY0OTU4OSwiZXhwIjoxNjg5NjUzMTg5LCJlbWFpbCI6ImphY2tAdXZpYy5jYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYWNrQHV2aWMuY2EiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SnUXDrKTpecK6sRpaX7V9gzva7yz_z1c85lU6rrlM6OFlVTyKUchzNvmNKu6wNDDUeItY1bHGPdvE321sxDLmXQ6rdI_8xG8pKUZJgmDjS-FzsXP7lQEd9ovMcklPmO3qLw2noCkMNjDOHEfSYql0itUHrGJXIdtwAra7xTbd9bPt1qreh4UDkNhTbtasnlXNXBZTiUQGkZ_NT0EdY_5erBrFSvFIvLCXkUP2e7rntp5Fkq9IFQO5-OMN48FMT4grOZ1lR4ALnQ17ey231kskcme8upEqelEw78dzIcRpU_O2JkRh6ks_dwu_MlUWXDAqkU8ac1nI_Y1kHhB6draIg
