
### Get hidden log list

GET http://127.0.0.1:8080/api/v1/hide-log/your-hide-log
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer abc

{
    "next": 1689647419058834
}


### Get hidden content log by id

GET http://127.0.0.1:8080/api/v1/hide-log/hide-log?id=1
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer abc
