### user standing

PATCH http://127.0.0.1:8080/api/v1/admin/user-standing
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4NzkxNDEzMywidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg3OTE0MTMzLCJleHAiOjE2ODc5MTc3MzMsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.3-XXlAs9aqgdN1nK7_pCkQfY53-MyKPWxiHoIdph_UAqOlLxfabMpOoRUb_e_3NBPFoQzLaQVRqgjOfgVELMrUIZuQkKLnrvB2Or-wX8psomnDNG2UXZNUsJBqSOK13K2bToVzbpXtB-nRGg2yzMw1m0RfmkETgeuOAHVZgTnerS4Kflsq4Bu3BFYb2woFFlzNuOAGdP6w_MPr9qPUjcGREMnSpLj9jYEHj5EZ2GCYXl5_jGnrkRvIPwu0YUcAOZfjgzSRX2UE1SjL3TPqUqpbFLOpOhq2KMKzaTEi5jlQQRox0q_Je8wDlG_xPcOcKqNbXf7Lag9MD46P8PO2lhQw

{
    "standing": "enabled"
}

### Manually trigger daily hottest cron job

# day format: YYYY-MM-DD for selecting when to run the cron job. It won't overwrite an already-ran job

POST http://127.0.0.1:8080/api/v1/admin/daily-hottest-cron?day=2023-06-21
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4NzkxNDEzMywidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg3OTE0MTMzLCJleHAiOjE2ODc5MTc3MzMsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.3-XXlAs9aqgdN1nK7_pCkQfY53-MyKPWxiHoIdph_UAqOlLxfabMpOoRUb_e_3NBPFoQzLaQVRqgjOfgVELMrUIZuQkKLnrvB2Or-wX8psomnDNG2UXZNUsJBqSOK13K2bToVzbpXtB-nRGg2yzMw1m0RfmkETgeuOAHVZgTnerS4Kflsq4Bu3BFYb2woFFlzNuOAGdP6w_MPr9qPUjcGREMnSpLj9jYEHj5EZ2GCYXl5_jGnrkRvIPwu0YUcAOZfjgzSRX2UE1SjL3TPqUqpbFLOpOhq2KMKzaTEi5jlQQRox0q_Je8wDlG_xPcOcKqNbXf7Lag9MD46P8PO2lhQw

### List the successfully ran daily hottest cron jobs

# you pass in the current day in milliseconds since unix epoch, and use that as the next cursor

GET http://127.0.0.1:8080/api/v1/admin/daily-hottest-crons?next=1687422462194 
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4NzkxNDEzMywidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg3OTE0MTMzLCJleHAiOjE2ODc5MTc3MzMsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.3-XXlAs9aqgdN1nK7_pCkQfY53-MyKPWxiHoIdph_UAqOlLxfabMpOoRUb_e_3NBPFoQzLaQVRqgjOfgVELMrUIZuQkKLnrvB2Or-wX8psomnDNG2UXZNUsJBqSOK13K2bToVzbpXtB-nRGg2yzMw1m0RfmkETgeuOAHVZgTnerS4Kflsq4Bu3BFYb2woFFlzNuOAGdP6w_MPr9qPUjcGREMnSpLj9jYEHj5EZ2GCYXl5_jGnrkRvIPwu0YUcAOZfjgzSRX2UE1SjL3TPqUqpbFLOpOhq2KMKzaTEi5jlQQRox0q_Je8wDlG_xPcOcKqNbXf7Lag9MD46P8PO2lhQw


### Get Feedback By ID

GET http://127.0.0.1:8080/api/v1/admin/feedback/9
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4NzkxNDEzMywidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg3OTE0MTMzLCJleHAiOjE2ODc5MTc3MzMsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.3-XXlAs9aqgdN1nK7_pCkQfY53-MyKPWxiHoIdph_UAqOlLxfabMpOoRUb_e_3NBPFoQzLaQVRqgjOfgVELMrUIZuQkKLnrvB2Or-wX8psomnDNG2UXZNUsJBqSOK13K2bToVzbpXtB-nRGg2yzMw1m0RfmkETgeuOAHVZgTnerS4Kflsq4Bu3BFYb2woFFlzNuOAGdP6w_MPr9qPUjcGREMnSpLj9jYEHj5EZ2GCYXl5_jGnrkRvIPwu0YUcAOZfjgzSRX2UE1SjL3TPqUqpbFLOpOhq2KMKzaTEi5jlQQRox0q_Je8wDlG_xPcOcKqNbXf7Lag9MD46P8PO2lhQw

### Get Feedback List

GET http://127.0.0.1:8080/api/v1/admin/feedback?limit=10&page=4
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMDNhZTdmNDczZjJjNmIyNTI3NmMwNjM2MGViOTk4ODdlMjNhYTkiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4NzkxNDEzMywidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg3OTE0MTMzLCJleHAiOjE2ODc5MTc3MzMsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.3-XXlAs9aqgdN1nK7_pCkQfY53-MyKPWxiHoIdph_UAqOlLxfabMpOoRUb_e_3NBPFoQzLaQVRqgjOfgVELMrUIZuQkKLnrvB2Or-wX8psomnDNG2UXZNUsJBqSOK13K2bToVzbpXtB-nRGg2yzMw1m0RfmkETgeuOAHVZgTnerS4Kflsq4Bu3BFYb2woFFlzNuOAGdP6w_MPr9qPUjcGREMnSpLj9jYEHj5EZ2GCYXl5_jGnrkRvIPwu0YUcAOZfjgzSRX2UE1SjL3TPqUqpbFLOpOhq2KMKzaTEi5jlQQRox0q_Je8wDlG_xPcOcKqNbXf7Lag9MD46P8PO2lhQw


