### user standing

PATCH http://127.0.0.1:8080/api/v1/admin/user-standing
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODI2Mjc3MSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4MjYyNzcxLCJleHAiOjE2ODgyNjYzNzEsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pn6kuVfL4FeqeYtclKG_KavoZti2xizdhSimumTtNLY5GJCoLCufhu1IxeoP7emp2YJyvrdDjF4eKIWsdV39xnDpgTApUVP7CXn0iXVytl5sfH5dv_Scg4oUtmJUjI0x05l-ydm1g6OsBfpnweyTowciJC0XpTK3NowV4THSpqzekuHjCNklv5hCS10t4kTpjsROrAWYRsq-49VxH_uvNJ_FOPFCibW31OWfEixtxaVfHxLSy3AEoWEsxFipWJ2Az63S6ZNzvBht3H4usIwSpEYYFp7rfOJce3TJw7VWmKHGs5sv81MobnTYdaY0DvjdqsEW4RjL_-btoualgAi4Ew

{
    "standing": "enabled"
}

### Manually trigger daily hottest cron job

# day format: YYYY-MM-DD for selecting when to run the cron job. It won't overwrite an already-ran job

POST http://127.0.0.1:8080/api/v1/admin/daily-hottest-cron?day=2023-06-21
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODI2Mjc3MSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4MjYyNzcxLCJleHAiOjE2ODgyNjYzNzEsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pn6kuVfL4FeqeYtclKG_KavoZti2xizdhSimumTtNLY5GJCoLCufhu1IxeoP7emp2YJyvrdDjF4eKIWsdV39xnDpgTApUVP7CXn0iXVytl5sfH5dv_Scg4oUtmJUjI0x05l-ydm1g6OsBfpnweyTowciJC0XpTK3NowV4THSpqzekuHjCNklv5hCS10t4kTpjsROrAWYRsq-49VxH_uvNJ_FOPFCibW31OWfEixtxaVfHxLSy3AEoWEsxFipWJ2Az63S6ZNzvBht3H4usIwSpEYYFp7rfOJce3TJw7VWmKHGs5sv81MobnTYdaY0DvjdqsEW4RjL_-btoualgAi4Ew

### List the successfully ran daily hottest cron jobs

# you pass in the current day in milliseconds since unix epoch, and use that as the next cursor

GET http://127.0.0.1:8080/api/v1/admin/daily-hottest-crons?next=1687422462194 
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODI2Mjc3MSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4MjYyNzcxLCJleHAiOjE2ODgyNjYzNzEsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pn6kuVfL4FeqeYtclKG_KavoZti2xizdhSimumTtNLY5GJCoLCufhu1IxeoP7emp2YJyvrdDjF4eKIWsdV39xnDpgTApUVP7CXn0iXVytl5sfH5dv_Scg4oUtmJUjI0x05l-ydm1g6OsBfpnweyTowciJC0XpTK3NowV4THSpqzekuHjCNklv5hCS10t4kTpjsROrAWYRsq-49VxH_uvNJ_FOPFCibW31OWfEixtxaVfHxLSy3AEoWEsxFipWJ2Az63S6ZNzvBht3H4usIwSpEYYFp7rfOJce3TJw7VWmKHGs5sv81MobnTYdaY0DvjdqsEW4RjL_-btoualgAi4Ew


### Get Feedback By ID

GET http://127.0.0.1:8080/api/v1/admin/feedback/9
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODI2Mjc3MSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4MjYyNzcxLCJleHAiOjE2ODgyNjYzNzEsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pn6kuVfL4FeqeYtclKG_KavoZti2xizdhSimumTtNLY5GJCoLCufhu1IxeoP7emp2YJyvrdDjF4eKIWsdV39xnDpgTApUVP7CXn0iXVytl5sfH5dv_Scg4oUtmJUjI0x05l-ydm1g6OsBfpnweyTowciJC0XpTK3NowV4THSpqzekuHjCNklv5hCS10t4kTpjsROrAWYRsq-49VxH_uvNJ_FOPFCibW31OWfEixtxaVfHxLSy3AEoWEsxFipWJ2Az63S6ZNzvBht3H4usIwSpEYYFp7rfOJce3TJw7VWmKHGs5sv81MobnTYdaY0DvjdqsEW4RjL_-btoualgAi4Ew

### Get Feedback List

GET http://127.0.0.1:8080/api/v1/admin/feedback?limit=10&page=4
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODI2Mjc3MSwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4MjYyNzcxLCJleHAiOjE2ODgyNjYzNzEsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.pn6kuVfL4FeqeYtclKG_KavoZti2xizdhSimumTtNLY5GJCoLCufhu1IxeoP7emp2YJyvrdDjF4eKIWsdV39xnDpgTApUVP7CXn0iXVytl5sfH5dv_Scg4oUtmJUjI0x05l-ydm1g6OsBfpnweyTowciJC0XpTK3NowV4THSpqzekuHjCNklv5hCS10t4kTpjsROrAWYRsq-49VxH_uvNJ_FOPFCibW31OWfEixtxaVfHxLSy3AEoWEsxFipWJ2Az63S6ZNzvBht3H4usIwSpEYYFp7rfOJce3TJw7VWmKHGs5sv81MobnTYdaY0DvjdqsEW4RjL_-btoualgAi4Ew


