#!/usr/bin/env bash

export APPCHECK_TOKEN="test_token"
export POSTGRES_DSN="postgres://postgres:postgres@localhost:5432/confesi?sslmode=disable"
export CIPHER_KEY="thisis32bitlongpassphraseimusing"

echo $CIPHER_KEY

go test $1 -v
