### Submit a feedback report

POST http://127.0.0.1:8080/api/v1/feedback/create
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5N2U3ZWVlY2YwMWM4MDhiZjRhYjkzOTczNDBiZmIyOTgyZTg0NzUiLCJ0eXAiOiJKV1QifQ.eyJwcm9maWxlX2NyZWF0ZWQiOnRydWUsInJvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NvbmZlc2ktc2VydmVyLWRldiIsImF1ZCI6ImNvbmZlc2ktc2VydmVyLWRldiIsImF1dGhfdGltZSI6MTY4ODYzODQ0MiwidXNlcl9pZCI6IjRYZzZ1c0Z6YUphc0NCdXY2RHgybXJ3U3NadDEiLCJzdWIiOiI0WGc2dXNGemFKYXNDQnV2NkR4Mm1yd1NzWnQxIiwiaWF0IjoxNjg4NjM4NDQyLCJleHAiOjE2ODg2NDIwNDIsImVtYWlsIjoibWF0dEB1dmljLmNhIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1hdHRAdXZpYy5jYSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.UkXaW1vOVE0NqB6MYk2M0LhOSVpTTdF1a9YBWXEJvC1-Urv8oRg8m15kUwBLuF2bdCRNCx-F7w6GAd1HFRrlpTT80jpDUNDZX01WmhEO5qIGhli_NwUQbXNJo6eN6vL6tWSmLROuCFHtEP-jm5GC0Jw28NQn0iZR9X7ejcRLYwprFMWt93KckK4k7Mo1G0K_NtEveLXGaPmY2vrEM33qZdP8FOojJaH35Cwcy_gmjF5TglpJLdf-hw1FoOIpupMba0qWZdNQN7kLu40hX_FmZaM6P03k-GlDAafRMDxx_z01w17sZQNboaUH8Nta5q9FyPy5Zyjs3zm3geLCqVKZjA

{
    "message": "WOAH THIS WAS SUCH AN AMAZING APP I CAN'T BELEIVE YOU DID IT!",
    "type": "bug"
}