### Submit a feedback report

POST http://127.0.0.1:8080/api/v1/feedback/create
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer abc

{
    "message": "WOAH THIS WAS SUCH AN AMAZING APP I CAN'T BELEIVE YOU DID IT!",
    "type": "bug"
}
