POST http://127.0.0.1:8080/api/v1/auth/register
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJkM2E0YTllYjY0OTk0YzUxM2YyYzhlMGMwMTY1MzEzN2U5NTg3Y2EiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXVkIjoiY29uZmVzaS1zZXJ2ZXItZGV2IiwiYXV0aF90aW1lIjoxNjg1MjU0MTQ0LCJ1c2VyX2lkIjoiQUxpRkJ3TEJkM2g4b0N4WmdVWjViRzNaT05CMyIsInN1YiI6IkFMaUZCd0xCZDNoOG9DeFpnVVo1YkczWk9OQjMiLCJpYXQiOjE2ODUyNTQxNDUsImV4cCI6MTY4NTI1Nzc0NSwiZW1haWwiOiJjbGllbnQ0QGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNsaWVudDRAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.scLU2F9iiEnkXjD8pnxGgZ844VeW9FMADScRgJpb8daFnsE0doJEnxLYLQLvSbRo9myHsSwT5Zkr2hX3le5HGiwI1nID5KddiM2sdoOVdUtKreHfgUteLhH-iQJc-YfllPKKntLhf7EnJ8ozYWsBayYcUVBO64KTkIocaSApjChRZ0UtHTLm907yYPa7auf89boC8WSuzdzdzuq2lHf1GXIlwI5Sua1Ufqmvscc8VMvMr4kPQA29k7OHGTc8z9hZDZk1X9AFLG2lKRHf4NKeRdlbx6FFZ2LXrKsWkx8S4rx7dKwEuVA7vKCAW5MO0fIU7iThlXF9yrr2BqQj_NPvoQ