###! BE CAREFUL THIS IS LIVE!!! DON'T SEND EMAILS TO REAL PEOPLE!!!

### Register 

POST http://127.0.0.1:8080/api/v1/auth/register
Content-Type: application/json

{
    "email": "oober@uvic.ca",
    "password": "mysecurepw$"
}

### Change email

PATCH http://127.0.0.1:8080/api/v1/auth/update-email
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6W10sInN5bmMiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2OTE3MzMzNzgsInVzZXJfaWQiOiJESDdrSUlQRHp5WjFZVTlWeWowd0xkbE1ya1AyIiwic3ViIjoiREg3a0lJUER6eVoxWVU5VnlqMHdMZGxNcmtQMiIsImlhdCI6MTY5MTczMzM3OCwiZXhwIjoxNjkxNzM2OTc4LCJlbWFpbCI6Imx1a2VtY2xlb25AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibHVrZW1jbGVvbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Qu0ZF8XtoybtGxXJ_NLDVCh_QdsrMStOjf8eJSlrIWyoWE6i-7u0_uBQzGEVVU2eqEhZhtfSHjx2yDw_tuV9LqP_-ErdJBz1ivsiLQ0DVgTHbAI_l9KVNKhicjWUeJTok0Pe-nor214aTf95Cr1b6MnC8Fr4DbJ35XxMokLnzs-BFCMWsyhZvsdHyRhR4H7EFxRbQbyjnDAaGVfa9AFpQHegA9sK9l1kD5iOPrz83SHSlvL_Gc2Q4bR8QluGXxMLRfFVwxYOJUn31_3BHKOC62ZWMfDeXIoRiP-UQWgaxfMUE1_YmPf9Vw5c9baNujR8yJdkCzUf1RlyZqjEBzWvgA

{
    "email": "use0129384r@uvic.ca"
}

### Resend email verification

POST http://127.0.0.1:8080/api/v1/auth/resend-verification-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6W10sInN5bmMiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2OTE3MzMzNzgsInVzZXJfaWQiOiJESDdrSUlQRHp5WjFZVTlWeWowd0xkbE1ya1AyIiwic3ViIjoiREg3a0lJUER6eVoxWVU5VnlqMHdMZGxNcmtQMiIsImlhdCI6MTY5MTczMzM3OCwiZXhwIjoxNjkxNzM2OTc4LCJlbWFpbCI6Imx1a2VtY2xlb25AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibHVrZW1jbGVvbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Qu0ZF8XtoybtGxXJ_NLDVCh_QdsrMStOjf8eJSlrIWyoWE6i-7u0_uBQzGEVVU2eqEhZhtfSHjx2yDw_tuV9LqP_-ErdJBz1ivsiLQ0DVgTHbAI_l9KVNKhicjWUeJTok0Pe-nor214aTf95Cr1b6MnC8Fr4DbJ35XxMokLnzs-BFCMWsyhZvsdHyRhR4H7EFxRbQbyjnDAaGVfa9AFpQHegA9sK9l1kD5iOPrz83SHSlvL_Gc2Q4bR8QluGXxMLRfFVwxYOJUn31_3BHKOC62ZWMfDeXIoRiP-UQWgaxfMUE1_YmPf9Vw5c9baNujR8yJdkCzUf1RlyZqjEBzWvgA

### Send password reset email

POST http://127.0.0.1:8080/api/v1/auth/send-password-reset-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJyb2xlcyI6W10sInN5bmMiOnRydWUsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb25mZXNpLXNlcnZlci1kZXYiLCJhdWQiOiJjb25mZXNpLXNlcnZlci1kZXYiLCJhdXRoX3RpbWUiOjE2OTE3MzMzNzgsInVzZXJfaWQiOiJESDdrSUlQRHp5WjFZVTlWeWowd0xkbE1ya1AyIiwic3ViIjoiREg3a0lJUER6eVoxWVU5VnlqMHdMZGxNcmtQMiIsImlhdCI6MTY5MTczMzM3OCwiZXhwIjoxNjkxNzM2OTc4LCJlbWFpbCI6Imx1a2VtY2xlb25AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibHVrZW1jbGVvbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Qu0ZF8XtoybtGxXJ_NLDVCh_QdsrMStOjf8eJSlrIWyoWE6i-7u0_uBQzGEVVU2eqEhZhtfSHjx2yDw_tuV9LqP_-ErdJBz1ivsiLQ0DVgTHbAI_l9KVNKhicjWUeJTok0Pe-nor214aTf95Cr1b6MnC8Fr4DbJ35XxMokLnzs-BFCMWsyhZvsdHyRhR4H7EFxRbQbyjnDAaGVfa9AFpQHegA9sK9l1kD5iOPrz83SHSlvL_Gc2Q4bR8QluGXxMLRfFVwxYOJUn31_3BHKOC62ZWMfDeXIoRiP-UQWgaxfMUE1_YmPf9Vw5c9baNujR8yJdkCzUf1RlyZqjEBzWvgA

{
    "email": "matthew@gmail.com"
}
