### Register

POST http://127.0.0.1:8080/api/v1/auth/register
Content-Type: application/json
X-AppCheck-Token: kXfeSRgYTnoUztu6MO8FndqiRayoBaJqyDKQmoqvX3V9sZVlep/cm7cP!mgd-B9H

{
    "email": "shnaug12@uvic.ca",
    "password": "mysecurepw$",
    "year_of_study": 1,
    "faculty": "ENG"
}