// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/posts/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-AppCheck-Token": []
                    }
                ],
                "description": "Create a post with the given title and body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create a Post.",
                "parameters": [
                    {
                        "description": "The title and/or body of the post",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"title\": \"My Title\",\n \"body\": \"My Body\"\n}"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.Created"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.Created": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "null"
                },
                "value": {
                    "type": "string",
                    "example": "null"
                }
            }
        },
        "docs.ServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "server error"
                },
                "value": {
                    "type": "string",
                    "example": "null"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "X-AppCheck-Token": {
            "type": "apiKey",
            "name": "X-AppCheck-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Confesi dev-only API docs",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
