basePath: /api/v1
externalDocs:
  description: GitHub
  url: https://github.com/mattrltrent/confesi-server
host: localhost:8080
info:
  contact: {}
  title: Confesi dev-only API docs
  version: "1.0"
paths: {}
swagger: "2.0"
