basePath: /api/v1
definitions:
  docs.Created:
    properties:
      error:
        example: "null"
        type: string
      value:
        example: "null"
        type: string
    type: object
  docs.ServerError:
    properties:
      error:
        example: server error
        type: string
      value:
        example: "null"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Confesi dev-only API docs
  version: "1.0"
paths:
  /posts/create:
    post:
      consumes:
      - application/json
      description: Create a post with the given title and body.
      parameters:
      - description: The title and/or body of the post
        in: body
        name: Body
        required: true
        schema:
          example: |-
            {
             "title": "My Title",
             "body": "My Body"
            }
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/docs.Created'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/docs.ServerError'
      security:
      - BearerAuth: []
      - X-AppCheck-Token: []
      summary: Create a Post.
      tags:
      - Posts
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
  X-AppCheck-Token:
    in: header
    name: X-AppCheck-Token
    type: apiKey
swagger: "2.0"
