basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  title: Confesi dev-only API docs
  version: "1.0"
paths:
  /posts/create:
    post:
      consumes:
      - application/json
      description: Create a post with the given title and body.
      parameters:
      - description: The title and body of the post
        in: body
        name: Body
        required: true
        schema:
          example: |-
            {
             "title": "My Title",
             "body": "My Body"
            }
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create a Post.
      tags:
      - Posts
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
