name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CIPHER_KEY: ${{ secrets.CIPHER_KEY }}
      CIPHER_NONCE: ${{ secrets.CIPHER_NONCE }}
      HKDF_SECRET: ${{ secrets.HKDF_SECRET }}
      REDIS_CONN: ${{ secrets.REDIS_CONN }}
      PUBLIC_DOC_ACCESS: ${{ secrets.PUBLIC_DOC_ACCESS }}
      MASK_SECRET: ${{ secrets.MASK_SECRET }}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

