name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIPHER_KEY: ${{ secrets.CIPHER_KEY }}
      CIPHER_NONCE: ${{ secrets.CIPHER_NONCE }}
      HKDF_SECRET: ${{ secrets.HKDF_SECRET }}
      REDIS_CONN: ${{ secrets.REDIS_CONN }}
      PUBLIC_DOC_ACCESS: ${{ secrets.PUBLIC_DOC_ACCESS }}
      MASK_SECRET: ${{ secrets.MASK_SECRET }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.2'
          
      - name: Run unit tests
        run: ./scripts/test ./...
