name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


## Secrets I want to be in the env file for the unit tests


# CIPHER_KEY="7571DFF385A22617"

# CIPHER_NONCE="47363bcf91a1545668f0fd7a"

# HKDF_SECRET="some-secret-string"

# REDIS_CONN="redis:6379"

# PUBLIC_DOC_ACCESS=true

# MASK_SECRET="your_16_byte_key"




jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIPHER_KEY: ${{ secrets.CIPHER_KEY }}
      CIPHER_NONCE: ${{ secrets.CIPHER_NONCE }}
      HKDF_SECRET: ${{ secrets.HKDF_SECRET }}
      REDIS_CONN: ${{ secrets.REDIS_CONN }}
      PUBLIC_DOC_ACCESS: ${{ secrets.PUBLIC_DOC_ACCESS }}
      MASK_SECRET: ${{ secrets.MASK_SECRET }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.2'
          
      - name: Run unit tests
        run: ./scripts/test ./...
